# Generated by Django 6.0.1 on 2026-02-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_event_event_date_event_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='email_id',
            field=models.EmailField(default='example123@gmail.com', max_length=254),
        ),
    ]
