name: CrowdDense CI/CD Pipeline

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Stack
        # We don't need the .env file to build the image
        run: docker compose -f crowd_monitoring/docker-compose.yml build

      - name: Run Django Tests
        # We inject ALL secrets directly into the container here
        env:
          DATABASE_URL: postgis://postgres:${{ secrets.POSTGRES_PASSWORD }}@db:5432/postgres
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_TRIAL_NUMBER: ${{ secrets.TWILIO_TRIAL_NUMBER }}
        run: docker compose -f crowd_monitoring/docker-compose.yml run web python manage.py test
    
