name: CrowdDense CI/CD Pipeline

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "TWILIO_ACCOUNT_SID=${{ secrets.TWILIO_ACCOUNT_SID }}" >> crowd_monitoring/.env
          echo "TWILIO_AUTH_TOKEN=${{ secrets.TWILIO_AUTH_TOKEN }}" >> crowd_monitoring/.env
          echo "TWILIO_TRIAL_NUMBER=${{ secrets.TWILIO_TRIAL_NUMBER }}" >> crowd_monitoring/.env

      - name: Build Docker Stack
        run: docker compose -f crowd_monitoring/docker-compose.yml build

      - name: Run Django Tests
        run: docker compose -f crowd_monitoring/docker-compose.yml run web python manage.py test
